# Generated by Django 5.2.13 on 2026-08-03 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metric_collection", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consent",
            options={"ordering": ("-created", "-pk")},
        ),
    ]
