import uuid
from urllib.parse import urlparse

import requests
from openwisp_utils.utils import retryable_request as utils_retryable_request

from .utils import retryable_request


class GitHub:
    """A client for interacting with the GitHub API."""

    def __init__(self, token, repo):
        if not token:
            raise ValueError("GitHub token is required.")
        if not repo:
            raise ValueError("GitHub repository name (e.g., 'owner/repo') is required.")
        self.token = token
        self.repo = repo
        self.base_url = f"https://api.github.com/repos/{self.repo}"
        self.headers = {
            "Authorization": f"token {self.token}",
            "Accept": "application/vnd.github.v3+json",
        }

    def create_pr(self, head, base, title):
        """Creates a pull request on GitHub."""
        url = f"{self.base_url}/pulls"
        payload = {
            "title": title,
            "head": head,
            "base": base,
            "body": "**Note**: This PR was automatically generated by the `openwisp-utils` releaser tool.",
        }
        response = retryable_request(
            url=url, method="post", headers=self.headers, json=payload
        )
        return response.json()["html_url"]

    def is_pr_merged(self, pr_url):
        """Checks if a pull request has been merged."""
        pr_number = pr_url.rstrip("/").split("/")[-1]
        url = f"{self.base_url}/pulls/{pr_number}"
        response = retryable_request(method="get", url=url, headers=self.headers)
        return response.json().get("merged", False)

    def get_pr(self, pr_url):
        """Returns metadata for a pull request in the configured repository."""
        parsed_url = urlparse(pr_url)
        path = parsed_url.path.strip("/").split("/")
        if (
            parsed_url.scheme not in {"http", "https"}
            or parsed_url.netloc != "github.com"
            or len(path) != 4
            or "/".join(path[:2]) != self.repo
            or path[2] != "pull"
            or not path[3].isdigit()
        ):
            raise ValueError(
                "The pull request URL must belong to the configured GitHub repository."
            )
        pr_number = path[3]
        url = f"{self.base_url}/pulls/{pr_number}"
        response = retryable_request(method="get", url=url, headers=self.headers)
        return response.json()

    def get_release(self, tag_name):
        """Returns the release for a tag, or None when it has not been created."""
        response = retryable_request(
            method="get",
            url=f"{self.base_url}/releases/tags/{tag_name}",
            headers=self.headers,
            allowed_status_codes=(404,),
        )
        if response.status_code == 404:
            return None
        return response.json()

    def find_pr(self, head, base, title):
        """Returns an existing matching pull request, regardless of its state."""
        response = retryable_request(
            method="get",
            url=f"{self.base_url}/pulls",
            headers=self.headers,
            params={"state": "all", "base": base, "per_page": 100},
        )
        for pull_request in response.json():
            if (
                pull_request.get("title") == title
                and pull_request.get("head", {}).get("ref") == head
                and pull_request.get("base", {}).get("ref") == base
            ):
                return pull_request
        return None

    def create_release(self, tag_name, title, body):
        """Creates a draft release on GitHub."""
        url = f"{self.base_url}/releases"
        payload = {
            "tag_name": tag_name,
            "name": title,
            "body": body,
            "draft": False,
            "prerelease": False,
        }
        response = retryable_request(
            method="post",
            url=url,
            headers=self.headers,
            json=payload,
            allowed_status_codes=(422,),
        )
        if response.status_code == 422:
            existing_release = self.get_release(tag_name)
            if existing_release:
                return existing_release["html_url"]
            response.raise_for_status()
        return response.json()["html_url"]

    def check_pr_creation_permission(self) -> tuple[bool, str]:
        """Checks for PR creation permissions.

        Returns:
            A tuple containing a boolean indicating success and a string
            with a detailed message.
        """
        try:
            repo_resp = utils_retryable_request(
                method="get", url=self.base_url, headers=self.headers
            )
            repo_resp.raise_for_status()
            base = repo_resp.json().get("default_branch", "master")

            me_resp = utils_retryable_request(
                method="get", url="https://api.github.com/user", headers=self.headers
            )
            me_resp.raise_for_status()
            login = me_resp.json()["login"]

            url = f"{self.base_url}/pulls"
            fake_branch = f"__perm_probe_{uuid.uuid4().hex[:8]}__"
            payload = {
                "title": "Permission Probe",
                "head": f"{login}:{fake_branch}",
                "base": base,
                "body": "This is a temporary probe to check permissions and should not be merged.",
            }

            # This request is expected to fail. A 422 status indicates we have permission
            # to attempt a PR, but the branch doesn't exist. Any other code is a failure.
            probe_resp = utils_retryable_request(
                method="post", url=url, headers=self.headers, json=payload
            )
            probe_resp.raise_for_status()

            # If the request succeeds (2xx), it's unexpected.
            return (
                False,
                "Github permissions check returned an unexpected success status.",
            )
        except requests.HTTPError as e:
            if e.response is not None and e.response.status_code == 422:
                return (True, "GitHub token has sufficient write permissions.")
            elif e.response is not None:
                details = e.response.text
                try:
                    json_resp = e.response.json()
                    details = json_resp.get("message", details)
                except requests.JSONDecodeError:
                    pass
                return (
                    False,
                    f"Github permission failed with HTTP {e.response.status_code}. Details: {details}",
                )
            else:
                return (False, f"Github permission failed with an HTTP error: {e}")
        except requests.RequestException as e:
            return (False, f"A network error occurred during permission check: {e}")
