# Generated by Django 4.2.7 on 2024-07-24 15:20

from django.db import migrations
import openwisp_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("test_project", "0007_radiusaccounting_start_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=openwisp_utils.fields.FallbackDecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                fallback=20.0,
                max_digits=4,
                null=True,
            ),
        ),
    ]
