# Generated by Django 4.2.20 on 2025-04-30 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_project", "0008_book_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelf",
            name="writers",
            field=models.ManyToManyField(
                blank=True,
                related_name="writer_of",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Writers",
            ),
        ),
    ]
