# Generated by Django 5.2.10 on 2026-02-06 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_project", "0009_shelf_writers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="shelf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="test_project.shelf",
            ),
        ),
    ]
