# Generated by Django 5.2.13 on 2026-08-03 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_project", "0009_shelf_writers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ("name", "pk")},
        ),
        migrations.AlterModelOptions(
            name="shelf",
            options={"ordering": ("-created", "-pk")},
        ),
    ]
