name: Stale PR Management

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: bot-autoassign-stale-pr-${{ github.repository }}
  cancel-in-progress: false

jobs:
  manage-stale-prs-python:
    if: github.repository == 'openwisp/openwisp-utils'
    runs-on: ubuntu-latest
    steps:
      - name: Generate Write Token
        id: generate-write-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.OPENWISP_BOT_APP_ID }}
          private-key: ${{ secrets.OPENWISP_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}

      - name: Generate Validation Token
        id: generate-validation-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.OPENWISP_BOT_APP_ID }}
          private-key: ${{ secrets.OPENWISP_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: >-
            OpenWISP-Website,django-rest-framework-gis,netengine,django-swappable-models,
            packet-legacy,netdiff,openVPNServer,netjsonconfig,netjsongraph.js,
            django-owm-legacy,openwisp-config,ansible-openwisp2,ansible-openwisp2-iptables,
            luci-openwisp,django-x509,ansible-freeitaliawifi-login-page,
            ansible-openwisp2-imagegenerator,openwisp-controller,openwisp-users,
            openwisp-docs,openwrt-zabbixd,openwisp-network-topology,openwisp-utils,
            django-loci,django-jsonschema-widget,coova-chilli-openwrt,openwisp-radius,
            openwisp-ipam,lxdock-openwisp2,docker-openwisp,openwisp-wifi-login-pages,
            openwisp-firmware-upgrader,openwisp-monitoring,openwrt-openwisp-monitoring,
            openwisp-notifications,openwisp-dev-env,django-flat-json-widget,
            ansible-ow-influxdb,ansible-wireguard-openwisp,ansible-openwisp-wifi-login-pages,
            openwisp-vxlan-updater,openwisp-sentry-utils,Stouts.postfix,openwisp-sphinx-theme,
            .github,django-readonly-issue-demo-30577,django-minify-compress-staticfiles,
            bot-testing-ground

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -e .[github_actions]

      - name: Run stale PR bot
        env:
          GITHUB_TOKEN: ${{ steps.generate-write-token.outputs.token }}
          GITHUB_VALIDATION_TOKEN: ${{ steps.generate-validation-token.outputs.token }}
          REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: >
          python .github/actions/bot-autoassign/__main__.py
          stale_pr
